#!/usr/bin/env bash
# Provisions a bare Ubuntu 24.04 droplet into a gateway host.
#
# Paste into DigitalOcean's "User data" field when creating the droplet, or
# scp it onto an existing box and run it as root. Idempotent: re-running
# upgrades the packages and restarts the stack without regenerating secrets.
#
#   Recommended droplet: 1 vCPU / 2 GB / 50 GB. The gateway container is
#   capped at 1 GB (see mem_limit below), so a 1 GB droplet has no room left
#   for the kernel, dockerd and cloudflared.
#
# Nothing here opens an inbound port. cloudflared dials out to Cloudflare and
# reaches the gateway over the compose network, so the only inbound rule on the
# box is SSH.
#
# The compose stanza below is a copy of deploy/compose.gateway.yml with the
# `build:` section dropped so it always pulls the published image rather than
# needing the source tree. If you change tuning there, change it here too.
set -euo pipefail

# Everything from here lands in the log rather than the void cloud-init
# usually swallows it into.
exec > >(tee -a /var/log/nidora-provision.log) 2>&1
echo "[provision] starting $(date -Is)"

# ---------------------------------------------------------------------------
# Configuration. The tunnel token is the one secret this script cannot invent.
# ---------------------------------------------------------------------------

# Published by .github/workflows/gateway.yml to GHCR and Docker Hub, both
# public — no registry login. Pin the commit-SHA tag instead of `latest` if you
# want a redeploy to be a decision rather than a side effect of the next merge.
INFERENCE_IMAGE="${INFERENCE_IMAGE:-ghcr.io/nidora-software/nidora-ai-inference/gateway:latest}"

# Leave empty and fill in /opt/nidora/.env after boot. Anything pasted into
# user data stays readable at the droplet's metadata endpoint for the life of
# the droplet — which is a poor home for a credential you cannot rotate
# silently.
INFERENCE_CF_TUNNEL_TOKEN="${INFERENCE_CF_TUNNEL_TOKEN:-}"

INSTALL_DIR=/opt/nidora

# ---------------------------------------------------------------------------
# Base system
# ---------------------------------------------------------------------------
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get upgrade -y
apt-get install -y ca-certificates curl gnupg jq ufw unattended-upgrades

# Security updates apply themselves. This box holds the fleet's agent secret
# and is reachable from the internet through the tunnel.
dpkg-reconfigure -f noninteractive unattended-upgrades

# 2 GB of swap on a 2 GB droplet. Never the plan, but it turns a memory spike
# during a burst of concurrent uploads into a slow minute instead of the OOM
# killer choosing a process for you.
if [ ! -f /swapfile ]; then
    fallocate -l 2G /swapfile
    chmod 600 /swapfile
    mkswap /swapfile
    swapon /swapfile
    echo '/swapfile none swap sw 0 0' >> /etc/fstab
    # The gateway is I/O-bound, not memory-hungry; prefer the page cache.
    sysctl -w vm.swappiness=10
    echo 'vm.swappiness=10' > /etc/sysctl.d/99-nidora.conf
fi

# Deny inbound by default. The gateway publishes no ports and cloudflared only
# needs egress, so SSH is the entire inbound surface.
ufw default deny incoming
ufw default allow outgoing
ufw allow OpenSSH
ufw --force enable

# ---------------------------------------------------------------------------
# Docker, from the official repository
# ---------------------------------------------------------------------------
if ! command -v docker >/dev/null 2>&1; then
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
        | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
    # shellcheck disable=SC1091  # /etc/os-release exists on the droplet, not on the linter's box
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
        > /etc/apt/sources.list.d/docker.list
    apt-get update -y
    apt-get install -y docker-ce docker-ce-cli containerd.io \
        docker-buildx-plugin docker-compose-plugin
fi

# Unbounded container logs are the most boring way to fill a 50 GB disk, and
# this gateway logs a line per dispatch.
cat > /etc/docker/daemon.json <<'EOF'
{
  "log-driver": "json-file",
  "log-opts": { "max-size": "10m", "max-file": "3" }
}
EOF
systemctl enable --now docker
systemctl restart docker

# ---------------------------------------------------------------------------
# The stack
# ---------------------------------------------------------------------------
mkdir -p "$INSTALL_DIR"

cat > "$INSTALL_DIR/compose.yml" <<EOF
# Generated by deploy/droplet-user-data.sh — mirrors deploy/compose.gateway.yml
# without the build stage, so this host never needs the source tree.
name: nidora-inference

services:
  inference-gateway:
    image: ${INFERENCE_IMAGE}
    restart: unless-stopped
    environment:
      PORT: "8080"
      DATA_DIR: /data
      LOG_LEVEL: \${INFERENCE_LOG_LEVEL:-info}

      GATEWAY_API_KEYS: \${INFERENCE_API_KEYS:?set INFERENCE_API_KEYS}
      AGENT_SHARED_SECRET: \${INFERENCE_AGENT_SECRET:?set INFERENCE_AGENT_SECRET}
      ADMIN_KEYS: \${INFERENCE_ADMIN_KEYS:-}

      LEASE_TTL_S: "120"
      MAX_POLL_WAIT_S: "25"
      JOB_TTL_S: "1080"
      MAX_ATTEMPTS: "2"

      ARTIFACT_TTL_HOURS: "24"
      JOB_RETENTION_DAYS: "7"
      MAX_INPUT_BYTES: "20971520"
      MAX_ARTIFACT_BYTES: "209715200"
      BODY_LIMIT_BYTES: "33554432"
      MAX_QUEUE_DEPTH: \${INFERENCE_MAX_QUEUE_DEPTH:-200}
    volumes:
      - inference-data:/data
    mem_limit: \${INFERENCE_MEM_LIMIT:-1g}
    healthcheck:
      test:
        - CMD
        - node
        - -e
        - "fetch('http://127.0.0.1:8080/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  inference-cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token \${INFERENCE_CF_TUNNEL_TOKEN:?set INFERENCE_CF_TUNNEL_TOKEN}
    depends_on:
      inference-gateway:
        condition: service_healthy

volumes:
  inference-data:
EOF

# Secrets are generated once and never regenerated: rewriting them on a re-run
# would lock out every pod and client at the same moment.
if [ ! -f "$INSTALL_DIR/.env" ]; then
    umask 077
    cat > "$INSTALL_DIR/.env" <<EOF
# Client API keys. Comma-separated — add the new one, migrate clients, drop the
# old one. That is the whole rotation procedure.
INFERENCE_API_KEYS=$(openssl rand -hex 32)

# Every pod holds this as GATEWAY_AGENT_SECRET. It lives on rented hardware, so
# treat it as compromise-prone and rotate it when you retire a provider account.
INFERENCE_AGENT_SECRET=$(openssl rand -hex 32)

# Optional; /v1/pods falls back to the client keys when unset.
INFERENCE_ADMIN_KEYS=

# From Cloudflare Zero Trust → Networks → Tunnels. Point the tunnel's public
# hostname at HTTP → inference-gateway:8080.
INFERENCE_CF_TUNNEL_TOKEN=${INFERENCE_CF_TUNNEL_TOKEN}
EOF
    chmod 600 "$INSTALL_DIR/.env"
fi

# systemd owns the stack so a reboot brings it back and `systemctl restart
# nidora-gateway` is the one command an operator needs.
cat > /etc/systemd/system/nidora-gateway.service <<EOF
[Unit]
Description=Nidora inference gateway
Requires=docker.service
After=docker.service network-online.target
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=${INSTALL_DIR}
ExecStartPre=/usr/bin/docker compose -f compose.yml pull --quiet
ExecStart=/usr/bin/docker compose -f compose.yml up -d --remove-orphans
ExecStop=/usr/bin/docker compose -f compose.yml down
TimeoutStartSec=300

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable nidora-gateway.service

# The data volume is the only copy of in-flight job state, and a full disk on a
# co-located box takes its neighbours down too. Warn while there is still time
# to act rather than discovering it from failed uploads.
cat > /usr/local/bin/nidora-disk-check <<'EOF'
#!/usr/bin/env bash
used=$(df --output=pcent /var/lib/docker | tail -1 | tr -dc '0-9')
if [ "$used" -ge 80 ]; then
    logger -t nidora-disk -p user.warning "docker filesystem ${used}% used"
fi
EOF
chmod +x /usr/local/bin/nidora-disk-check

cat > /etc/systemd/system/nidora-disk-check.service <<'EOF'
[Unit]
Description=Warn when the gateway data disk is filling up
[Service]
Type=oneshot
ExecStart=/usr/local/bin/nidora-disk-check
EOF

cat > /etc/systemd/system/nidora-disk-check.timer <<'EOF'
[Unit]
Description=Hourly gateway disk check
[Timer]
OnCalendar=hourly
Persistent=true
[Install]
WantedBy=timers.target
EOF
systemctl daemon-reload
systemctl enable --now nidora-disk-check.timer

# ---------------------------------------------------------------------------
# Start, if we have everything we need
# ---------------------------------------------------------------------------
if grep -q '^INFERENCE_CF_TUNNEL_TOKEN=.\+' "$INSTALL_DIR/.env"; then
    systemctl start nidora-gateway.service
    echo "[provision] stack started"
else
    echo "[provision] no tunnel token yet — stack NOT started."
    echo "[provision] set INFERENCE_CF_TUNNEL_TOKEN in ${INSTALL_DIR}/.env, then:"
    echo "[provision]   systemctl start nidora-gateway"
fi

echo
echo "[provision] secrets (also in ${INSTALL_DIR}/.env, mode 600):"
grep -E '^INFERENCE_(API_KEYS|AGENT_SECRET)=' "$INSTALL_DIR/.env"
echo "[provision] done $(date -Is)"
